_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 3
                - 13
                - 16
                - 55
            "4": 3.12.7
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
model:
    value:
        params:
            max_depth: 5
            n_estimators: 100
            random_state: 42
        type: RandomForestClassifier
wandb:
    value:
        experiment_name: rf-baseline
        project: iris-classifier
